version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.3.0
    ports:
    - 127.0.0.1:5775:5775/udp # accept zipkin.thrift over compact thrift protocol
    - 127.0.0.1:6831:6831/udp # accept jaeger.thrift over compact thrift protocol
    - 127.0.0.1:6832:6832/udp # accept jaeger.thrift over binary thrift protocol
    - 127.0.0.1:5778:5778 # serve configs
    - 127.0.0.1:16686:16686 # serve frontend
    - 127.0.0.1:14268:14268 # accept jaeger.thrift directly from clients
  
